# Generated by Django 5.2.4 on 2025-09-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragAPP', '0001_initial'),
    ]

    operations = [
    ]
