# Generated by Django 5.2.4 on 2025-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragAPP', '0002_auto_20250908_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextChunk',
        ),
    ]
